# Generated by Django 3.2.6 on 2021-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_rename_is_licensed_customertype_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_doc',
            field=models.ImageField(blank=True, null=True, upload_to='licenses'),
        ),
    ]
