# Generated by Django 3.2.6 on 2021-08-10 10:39

import apps.commons.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0005_auto_20210810_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csr',
            name='mobile',
            field=models.CharField(max_length=10, validators=[apps.commons.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10, validators=[apps.commons.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.CharField(max_length=10, validators=[apps.commons.utils.validate_phone]),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, validators=[apps.commons.utils.validate_phone])),
                ('image', models.ImageField(upload_to='admins')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
