# Generated by Django 3.2.6 on 2021-08-09 15:36

import apps.commons.utils
import apps.vehicle_rental.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoothManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_address', models.CharField(help_text='Enter your permanent address', max_length=50)),
                ('curr_address', models.CharField(help_text='Enter your current address', max_length=50)),
                ('mobile', models.PositiveIntegerField(help_text='Your mobile number', validators=[django.core.validators.MinLengthValidator(10), apps.commons.utils.validate_phone])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(help_text='Plate number like : BDE1234', max_length=7, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('seats', models.PositiveIntegerField(help_text='Enter available seats')),
                ('wheels_num', models.PositiveIntegerField(help_text='Enter wheels number of a vehicle')),
                ('manufacturing_year', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('mileage', models.PositiveIntegerField()),
                ('fare', models.PositiveIntegerField(help_text='Enter a fare for per day')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', max_length=50)),
                ('vehicle_type', models.CharField(default='Car', max_length=10)),
                ('issued_by', models.OneToOneField(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), to='vehicle_rental.boothmanager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.owner')),
                ('residing_booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_rental.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booth',
            name='manager',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicle_rental.boothmanager'),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(help_text='Plate number like : BDE1234', max_length=7, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('seats', models.PositiveIntegerField(help_text='Enter available seats')),
                ('wheels_num', models.PositiveIntegerField(help_text='Enter wheels number of a vehicle')),
                ('manufacturing_year', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('mileage', models.PositiveIntegerField()),
                ('fare', models.PositiveIntegerField(help_text='Enter a fare for per day')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', max_length=50)),
                ('vehicle_type', models.CharField(default='Bike', max_length=10)),
                ('issued_by', models.OneToOneField(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), to='vehicle_rental.boothmanager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.owner')),
                ('residing_booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_rental.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
