# Generated by Django 3.2.6 on 2021-08-10 10:39

import apps.commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0003_alter_boothmanager_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothmanager',
            name='mobile',
            field=models.CharField(max_length=10, validators=[apps.commons.utils.validate_phone]),
        ),
    ]
