# Generated by Django 3.2.6 on 2021-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0004_alter_boothmanager_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
