# Generated by Django 3.2.6 on 2021-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0006_auto_20210811_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='manufacturing_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturing_year',
            field=models.DateField(),
        ),
    ]
