# Generated by Django 3.2.6 on 2021-08-11 08:27

import apps.commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0007_auto_20210811_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='manufacturing_year',
            field=models.CharField(max_length=4, validators=[apps.commons.utils.is_number]),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturing_year',
            field=models.CharField(max_length=4, validators=[apps.commons.utils.is_number]),
        ),
    ]
