# Generated by Django 3.2.6 on 2021-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0008_auto_20210811_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default=0, upload_to='vehicles/bikes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='seats',
            field=models.PositiveIntegerField(default=2, help_text='Enter available seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=4, help_text='Enter available seats'),
        ),
    ]
