# Generated by Django 3.2.6 on 2021-08-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0009_auto_20210811_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='wheels_num',
            field=models.PositiveIntegerField(default=2, help_text='Enter wheels number of a vehicle'),
        ),
    ]
