# Generated by Django 3.2.6 on 2021-08-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0010_alter_bike_wheels_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='issued_by',
            new_name='issuer',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='issued_by',
            new_name='issuer',
        ),
    ]
