# Generated by Django 3.2.6 on 2021-08-11 09:53

import apps.vehicle_rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0011_auto_20210811_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='vehicles/cars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='issuer',
            field=models.ForeignKey(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), to='vehicle_rental.boothmanager'),
        ),
        migrations.AlterField(
            model_name='car',
            name='issuer',
            field=models.ForeignKey(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), to='vehicle_rental.boothmanager'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheels_num',
            field=models.PositiveIntegerField(default=4, help_text='Enter wheels number of a vehicle'),
        ),
    ]
