# Generated by Django 3.2.6 on 2021-08-11 10:37

import apps.commons.utils
import apps.vehicle_rental.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_auto_20210810_1624'),
        ('vehicle_rental', '0012_auto_20210811_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='manufacturing_year',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='plate_num',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='residing_booth',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='status',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='car',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='manufacturing_year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='plate_num',
        ),
        migrations.RemoveField(
            model_name='car',
            name='residing_booth',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(help_text='Plate number like : BDE1234', max_length=7, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('manufacturing_year', models.CharField(max_length=4, validators=[apps.commons.utils.is_number])),
                ('mileage', models.FloatField()),
                ('fare', models.PositiveIntegerField(help_text='Enter a fare for per day')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', max_length=50)),
                ('issuer', models.ForeignKey(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), to='vehicle_rental.boothmanager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.owner')),
                ('residing_booth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_rental.booth')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='vehicle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental.vehicle'),
            preserve_default=False,
        ),
    ]
