# Generated by Django 3.2.6 on 2021-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0013_auto_20210811_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('REQUESTED', 'REQUESTED'), ('RESERVED', 'RESERVED'), ('OTHER', 'OTHER')], default='AVAILABLE', max_length=50),
        ),
    ]
