# Generated by Django 3.2.6 on 2021-08-13 16:05

import apps.vehicle_rental.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_auto_20210811_2339'),
        ('vehicle_rental', '0014_alter_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('reserv_period', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('INPROGESS', 'INPROGRESS'), ('GRANTED', 'GRANTED'), ('DENIED', 'DENIED'), ('CANCELLED', 'CANCELLED')], default='INPROGRESS', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(auto_now=True)),
                ('pre_payment', models.FloatField()),
                ('fine', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('borrow_approver', models.ForeignKey(on_delete=models.SET(apps.vehicle_rental.models.BoothManager), related_name='bapprover', to='vehicle_rental.boothmanager')),
                ('reservation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental.reservationrequest')),
                ('submit_approver', models.ForeignKey(null=True, on_delete=models.SET(apps.vehicle_rental.models.BoothManager), related_name='sapprover', to='vehicle_rental.boothmanager')),
            ],
        ),
    ]
