# Generated by Django 3.2.6 on 2021-08-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0016_auto_20210814_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='retun_date',
            new_name='return_date',
        ),
    ]
