# Generated by Django 3.2.6 on 2021-08-14 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental', '0019_alter_reservation_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expected_return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
